trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: GitVersion@5
  displayName: 'Run GitVersion'
  inputs:
    preferBundledVersion: false
- task: CmdLine@2
  displayName: 'Restore yarn packages'
  inputs:
    script: 'yarn install --frozen-lockfile'
    workingDirectory: 'GetIt.UI'
- task: CmdLine@2
  displayName: 'Restore packages'
  inputs:
    script: 'dotnet restore'
- task: DotNetCoreCLI@2
  displayName: 'Build GetIt.Controller'
  inputs:
    command: 'build'
    projects: 'GetIt.Controller'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  displayName: 'Build GetIt.UI.Container'
  inputs:
    command: 'build'
    projects: 'GetIt.UI.Container'
    arguments: '-c Release'
- task: CmdLine@2
  displayName: 'Build GetIt.UI'
  inputs:
    script: 'yarn bundle'
    workingDirectory: 'GetIt.UI'
- task: CmdLine@2
  displayName: 'Build NuGet package'
  inputs:
    script: .paket\paket.exe pack --minimum-from-lock-file --version $(GitVersion.NuGetVersion) GetIt.Controller
- task: PublishPipelineArtifact@0
  displayName: 'Publish NuGet package as pipeline artifact'
  inputs:
    artifactName: 'GetIt.nupkg'
    targetPath: 'GetIt.Controller/GetIt.$(GitVersion.NuGetVersion).nupkg'
- task: DotNetCoreCLI@2
  displayName: 'Push NuGet package to internal feed'
  inputs:
    command: 'push'
    packagesToPush: 'GetIt.Controller/GetIt.$(GitVersion.NuGetVersion).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'GetIt'
- task: GitHubRelease@0
  displayName: 'Tag git commit'
  inputs:
    gitHubConnection: johannesegger
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.BuildNumber)'
    title: ''
    releaseNotesSource: 'input'
    releaseNotesFile: ''
    releaseNotes: ''
    assets: ''
    assetUploadMode: 'delete'
    isDraft: false
    isPreRelease: false
    addChangeLog: true
